development:
  adapter: postgresql
  database: photogallery
  username: dbadmin
  password: admin123
  socket: /var/run/postgresql
  port:   5432
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: photogallery-test
  username: dbadmin
  password: admin123
  socket: /var/run/postgresql
  port:   5432
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: photogallery_prod
  username: dbadmin
  password: admin123
  socket: /var/run/postgresql
  port:   5432
  host: localhost
  pool: 5
  timeout: 5000